### PR TITLE
Should fix #16

### LINKED ISSUE #16: Support different return types for Control/Candidate methods
This implementation depends on decisions made for #15.

Basically the idea is that sometimes the candidate code returns a different, but relatable value. For example:

```C#
public int ControlMethod(int foo)
{
    return 1;
}

public bool CandidateMethod(int foo)
{
    return true;
}
```

The candidate method now returns a `bool`, and while `bool` and `int` are different, you could easily map `1 -> true` and `0 -> false`.

This could be implemented creating a new interface `Experiment<TControl, TCandidate>` that would allow the user to specify different types for each method. In this case, providing a `Compare` method could even be required for the interface.

What do you think?

### PR DESCRIPTION
**Pull request by jlandheer**
Added support for custom comparing of results.

### CODE REVIEW

**Comment by Haacked** [comment]
Ack! There's another PR already intending to add custom result comparisons.

**Comment by jlandheer** [comment]
Ah, the power of looking before you code... The difference I see with @RichardDalton's code is the support for different return types (#15) which necessitates a custom comparer. His code looks much better though.

**Comment by Haacked** [comment]
Ok, how would you like to proceed. Unfortunately, I merged a big change that created merge conflicts for this branch.

**Comment by Haacked** [comment]
I'm going to close this one for now. Sorry about that. Feel free to look over the current implementation and let me know if you have thoughts to improve it.

**Comment by jlandheer** [comment]
No problem.

**Pull request closed without merging**
