### PR TITLE
Improved XML documentation

### PR DESCRIPTION
**Pull request by joncloud**
I added more XML documentation to several public types.

### CODE REVIEW

**Comment by Haacked** [comment]
Thanks! Looks like you need to resolve a merge conflict.

**Comment by joncloud** [comment]
Yup I saw that change go in earlier. I'll do a quick merge and it should be resolved later.

**Comment by joncloud** [comment]
@Haacked conflicts all handled.

**Comment by Haacked** [comment]
Really appreciate this!

[selfie-0](https://github.com/thieman/github-selfies/)

**Pull request merged**
