### PR TITLE
Duration of exceptions is measured too

### PR DESCRIPTION
**Pull request by jlandheer**
I thought it would be nice to know how long it takes to fail. My first pull request so hopefully it's ok.

### CODE REVIEW

**Comment by Haacked** [comment]
Oh, nice catch! We would have just left the stopwatch keep going. :smile:

[selfie-2](https://github.com/thieman/github-selfies/)

**Comment by jlandheer** [comment]
Haha! Cool, my first accepted pull-request!

**Comment by Haacked** [comment]
> Haha! Cool, my first accepted pull-request!

Ever?

**Comment by jlandheer** [comment]
Yessir! And an animated gif, my day has officially been made.

**Comment by Haacked** [comment]
My coworker made this one which is perhaps more appropriate to the context of timing exceptions.

**Comment by jlandheer** [comment]
Man, your head explodes like the dude on the backseat in Pulp Fiction.,,

**Pull request merged**
