### PR TITLE
Added NSubstitute to remove side effect testing antipattern

### PR DESCRIPTION
**Pull request by darcythomas**
Now with less side effects.

### CODE REVIEW

**Comment by Haacked** [comment]
Thanks, but I use NSubstitute these days.

**Comment by darcythomas** [comment]
I will switch in NSubsitute.
Out of curiously why do you use NSubsitute?

**Comment by Haacked** [comment]
Just like the syntax a bit better.
We've been using it with Octokit.net: https://github.com/octokit/octokit.net/blob/master/Octokit.Tests/Clients/AssigneesClientTests.cs

**Comment by darcythomas** [comment]
Ok I am a convert. I like NSubsitute.
I have swapped out Moq with NSubsitute now

**Comment by Haacked** [comment]
[selfie-1](https://github.com/thieman/github-selfies/)

Thanks!

**Pull request merged**
