### PR TITLE
Move to .NET Core

### PR DESCRIPTION
**Pull request by davezych**
Move to .NET Core. Targets `rc1-update1` runtime, `net451` and `dotnet5.2` frameworks. 

Even though `dotnet5.2` targets .NET Framework 4.5, we must explicitly target `net451` on it's own so the tests will run. (`xunit` and `NSubstitute` aren't compatible with net standard, and there are dep problems targeting only net standard things right now. See (https://github.com/dotnet/corefx/issues/5540)). 

@Haacked I moved everything to Net core, meaning all `csproj`'s are gone in favor of `xproj`'s and `project.json`'s. Since we're targeting `dotnet5.2` anyone targeting 4.5+ can consume the lib, and I didn't see a need to keep the old project structure around. If for whatever reason you want it I can restore it.

### CODE REVIEW

**Comment by Haacked** [comment]
Nice! Any ideas on getting to build on AppVeyor?

**Comment by davezych** [comment]
@Haacked I didn't realize you had CI set up already! 

I added an `appveyor.yml` build script that builds the projects and runs the tests.

**Comment by Haacked** [comment]
> I added an appveyor.yml build script that builds the projects and runs the tests.

SWEET! Let me try this out to make sure it still works in VS2015

**Comment by Haacked** [comment]
[selfie-0](https://github.com/thieman/github-selfies/)

Works great! Unfortunately, TestDriven.NET can't run these tests. But the built in test runner can.

**Comment by Haacked** [comment]
Want to help us script the creation of our nuget package next?

**Comment by jpsingleton** [comment]
@davezych @Haacked I can't get this to work on ASP.NET 5/Core RC1 Update 1, details in https://github.com/Haacked/Scientist.net/issues/35. Maybe I need an newer version of .NET Core?

**Pull request merged**
