### PR TITLE
Alpha 5 version bump 

### PR DESCRIPTION
**Pull request by davezych**

### CODE REVIEW

**Comment by davezych** [comment]
Remember to merge, let appveyor build and pull the build artifacts from master. :+1: 

(also, I didn't spend a ton of time on the release notes and had a hard time figuring out what was in the previous version, so the new features might be lacking...)

**Comment by Haacked** [comment]
:sparkles:

**Comment by Haacked** [comment]
@davezych Ok, I pushed alpha5. Can you try it out?

**Comment by davezych** [comment]
:+1: works like a champ.

**Pull request merged**
